AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Books API with the aws-serverless-java-container library

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  BooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler.GetBooksHandler::handleRequest
      Runtime: java8
      CodeUri: target/EquiDemo-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Booksv2API:
    Description: Booksv2API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/test/books'
    Export:
      Name: Booksv2API